server {
    listen 443 ssl; # managed by Certbot
    server_name miguelprogrammer-challenge.duckdns.org;

    # Certificados SSL (Caminhos padrão do Certbot)
    ssl_certificate /etc/letsencrypt/live/miguelprogrammer-challenge.duckdns.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/miguelprogrammer-challenge.duckdns.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # 1. API JAVA
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. GRAFANA (CORRIGIDO PARA SUBPATH)
    location /grafana/ {
        proxy_pass http://localhost:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /grafana;
        proxy_cookie_path / /grafana/;

        # Ajustes de redirecionamento para evitar tela branca
        proxy_buffering off;
        proxy_redirect http:// https://;
        proxy_redirect / /grafana/;
    }

    # 3. PROMETHEUS (se precisar)
    location /prometheus/ {
        proxy_pass http://localhost:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Redirecionamento de HTTP para HTTPS
server {
    listen 80;
    server_name miguelprogrammer-challenge.duckdns.org;
    return 301 https://$host$request_uri;
}

