name: Pipeline CI/CD

on:
  push:
    branches:
      - developer

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  build-e-entrega:
    name: "1. Build, Teste e Docker"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build Maven
        run: mvn clean package -DskipTests

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/product-comparison-app:latest .

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/product-comparison-app:latest

  deploy-ec2:
    name: "2. Deploy AWS EC2"
    needs: build-e-entrega
    runs-on: ubuntu-latest

    steps:

      - name: Deploy Completo EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          timeout: 60s
          command_timeout: 30m

          script: |

            echo "========== LOGIN DOCKER =========="

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
              -u "${{ secrets.DOCKERHUB_USERNAME }}" \
              --password-stdin

            echo "========== PULL IMAGE =========="

            docker pull \
              ${{ secrets.DOCKERHUB_USERNAME }}/product-comparison-app:latest

            echo "========== REDE =========="

            docker network create monitoring-network || true

            echo "========== REMOVENDO CONTAINERS =========="

            docker stop \
              product-comparison-app \
              prometheus \
              grafana || true

            docker rm \
              product-comparison-app \
              prometheus \
              grafana || true

            echo "========== PROMETHEUS CONFIG =========="

            mkdir -p ~/prometheus

            cat <<EOF > ~/prometheus/prometheus.yml
            global:
              scrape_interval: 5s

            scrape_configs:
              - job_name: 'spring-boot-app'
                metrics_path: '/actuator/prometheus'

                static_configs:
                  - targets: ['product-comparison-app:8080']
            EOF

            echo "========== SUBINDO SPRING =========="

            docker run -d \
              --name product-comparison-app \
              --restart always \
              --network monitoring-network \
              -p 8080:8080 \
              -e SPRING_SQL_INIT_MODE=always \
              -e TRACING_ENABLED=false \
              -e DATABASE_USERNAME=sa \
              -e DATABASE_PASSWORD= \
              -e DATABASE_URL="jdbc:h2:mem:product;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE" \
              ${{ secrets.DOCKERHUB_USERNAME }}/product-comparison-app:latest

            echo "========== SUBINDO PROMETHEUS =========="

            docker run -d \
              --name prometheus \
              --restart always \
              --network monitoring-network \
              -p 9090:9090 \
              -v ~/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
              prom/prometheus \
              --config.file=/etc/prometheus/prometheus.yml

            echo "========== SUBINDO GRAFANA =========="

            docker volume create grafana-storage || true

            docker run -d \
              --name grafana \
              --restart always \
              --network monitoring-network \
              -p 3000:3000 \
              -v grafana-storage:/var/lib/grafana \
              -e GF_SERVER_DOMAIN=miguelprogrammer-challenge.duckdns.org \
              -e GF_SERVER_ROOT_URL=https://miguelprogrammer-challenge.duckdns.org/grafana/ \
              -e GF_SERVER_SERVE_FROM_SUB_PATH=true \
              -e GF_SECURITY_ADMIN_PASSWORD=admin123 \
              grafana/grafana:latest

            echo "========== AGUARDANDO APP =========="

            sleep 25

            echo "========== HEALTHCHECK =========="

            curl -f http://localhost:8080/actuator/health

            echo "========== CLEANUP =========="

            docker image prune -f

  gerar-trafego:
    name: "3. Alimentar Grafana"
    needs: deploy-ec2
    runs-on: ubuntu-latest

    steps:

      - name: Esperar Deploy
        run: sleep 20

      - name: Instalar hey
        run: |
          go install github.com/rakyll/hey@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Gerar carga 25 RPS
        run: |
          hey \
            -q 25 \
            -z 15s \
            https://miguelprogrammer-challenge.duckdns.org/api/v1/products
